### ISSUE TITLE
Gems: Add GeoCombine

### ISSUE THREAD

**Issue by ewlarson** [UWM-Libraries/GeoDiscovery#10]
Review codebase and write rake task to assist in harvesting Aardvark datasets from OGM contributors.

**Comment by srappel** [comment]
Just FYI we do have a [UWM Libraries fork](https://github.com/UWM-Libraries/Geocombine) of GeoCombine where Nathan has worked on the XSLT:

**Comment by srappel** [comment]
I synced the changes from the GBL sprint to our [local repo](https://github.com/UWM-Libraries/GeoCombine)
