### ISSUE TITLE
UWM SVG icon

### ISSUE THREAD

**Issue by srappel** [UWM-Libraries/GeoDiscovery#15]
We need an svg icon that will show up on our application and anyone's application who harvest's our metadata from OpenGeoMetadata.

See https://geoblacklight.org/docs/customization/adding_svg_icons/

**Comment by srappel** [comment]
I think this would make a good icon:

![UWM_Logo-Vertical_Black](https://user-images.githubusercontent.com/12561339/219716590-6dbbca50-6fc9-491b-a825-e54f1ef7a08f.png)

**Comment by ewlarson** [comment]
### Greyscale SVG for GBL

![uwm-logomark-greyscale-text-banner](https://user-images.githubusercontent.com/69827/223213941-08261e3a-b16d-4753-bf93-928a1df93fd0.svg)

**Comment by ewlarson** [comment]
Example screenshot in the application

<img width="1713" alt="Screenshot 2023-03-06 at 2 06 48 PM" src="https://user-images.githubusercontent.com/69827/223219069-1dfd6bb1-6448-46ed-881c-64a31356a79e.png">

**Comment by ewlarson** [comment]
Open PR with GeoBlacklight to integrate the new logo:
https://github.com/geoblacklight/geoblacklight/pull/1280
