### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by srappel** [UWM-Libraries/GeoDiscovery#33]
Test and confirm that Google Analytics is working

**Comment by greatfog** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=G-SBMT3M6EV2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-SBMT3M6EV2');
</script>
