### ISSUE TITLE
Logo - UWM Libraries 

### ISSUE THREAD

**Issue by ewlarson** [UWM-Libraries/GeoDiscovery#9]
Find the UWM Libraries stacked application logo.

**Comment by srappel** [comment]
So we don't have a nice square one like I was hoping for. We have two we can work with for now. I'm curious what a more rectangular option would look like.

Option 1: (Non-transparent, yellow banner)
![UWM_Social_Badge_Libraries_2023_white](https://user-images.githubusercontent.com/12561339/219687585-e4e1dcd7-aed5-4878-81bc-d1d2042be1d6.png)

Option 2: (Transparent, blackish)
![transparentLibrariesBW](https://user-images.githubusercontent.com/12561339/219688072-6599c1a0-756f-4601-bba4-f9707fe1cbcb.png)

We could bump that "UWM Libraries" text up a bit.

**Comment by srappel** [comment]
Honestly, I would be happier with the UWM Logo (as-is) than either of these options.

**Comment by srappel** [comment]
Something like the logo from the UWM YouTube channel (grey bg) could look nice.

https://www.youtube.com/uwmnews

**Comment by ewlarson** [comment]
The SVGs

### White Text Yellow Banner
![uwm-logomark-whiteTextYellowBanner](https://user-images.githubusercontent.com/69827/223176550-a39811a7-b11d-4a23-8ce6-75001450e732.svg)

### BlackTextBlackBanner
![uwm-logomark-BlackTextBanner](https://user-images.githubusercontent.com/69827/223176551-ec5626e5-9990-4905-9a72-0545cdc9b4dc.svg)

**Comment by ewlarson** [comment]
Some quick screen shots for feedback. Let me know your favorite.

### Circle
<img width="1713" alt="Screenshot 2023-03-06 at 12 49 37 PM" src="https://user-images.githubusercontent.com/69827/223203597-0194d0a7-d01b-4416-baaa-3567429ff1bb.png">

### Square
<img width="1713" alt="Screenshot 2023-03-06 at 12 49 49 PM" src="https://user-images.githubusercontent.com/69827/223203622-f95c81ff-f94c-4829-8060-79fb487a5004.png">

### Square (Less padding)
<img width="1713" alt="Screenshot 2023-03-06 at 12 50 42 PM" src="https://user-images.githubusercontent.com/69827/223203698-113bae6e-f8bc-4ef5-9cc4-cd6bb1580cda.png">

**Comment by srappel** [comment]
My favorite is the circle followed by the square with less padding.

**Comment by ewlarson** [comment]
One more here...

### Square (no yellow padding)
<img width="1713" alt="Screenshot 2023-03-06 at 12 55 57 PM" src="https://user-images.githubusercontent.com/69827/223204667-94a2d74b-6f66-4f81-89fa-4bd792762486.png">

**Comment by srappel** [comment]
I like that second best, but still prefer the circle.
